# Generated by Django 3.1.1 on 2020-11-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlenderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
