# Generated by Django 2.2.5 on 2020-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendermodel',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Contract file (Blend)'),
        ),
    ]
